import * as THREE from 'three';
export const appearanceDefaults={mode:'realistic',skin_color:'#c99579',skin_tint:0,skin_lightness:.5,skin_detail:1,skin_roughness:.85,stubble_strength:.6,iris_strength:1,iris_color:'#795637',hair_lightness:.5,hair_color:'#ffffff',brow_color:'#463023',brow_density:1,clothing_color:'#ffffff',freckles:0,forehead:0,crow:0,under_eye:0,folds:0,marionette:0,lip_color:0,eye_makeup:0};
export const skinPresets=[['Porcelain rose','#ebc5b5'],['Fair neutral','#ddba9e'],['Light golden','#d3aa7c'],['Warm beige','#bf9474'],['Olive tan','#a58a64'],['Copper brown','#a37350'],['Medium neutral','#89634f'],['Rich warm brown','#68452f'],['Deep neutral','#49352c'],['Deep cool brown','#352b28']];
const stubbleImage=new Image();stubbleImage.src='./stubble-density.png?v=4096';stubbleImage.onload=()=>{signature='';window.dispatchEvent(new Event('stubble-ready'));};
let meshes=[],signature='',epoch=0,skinBase=null,skinTexture=null;
export function setupAppearance(objects){meshes=objects;for(const m of meshes){const mats=Array.isArray(m.material)?m.material:[m.material];m.userData.originalMaterials=mats.map(x=>({map:x.map,normalMap:x.normalMap,roughnessMap:x.roughnessMap,color:x.color.clone()}));if(m.userData.category==='body')skinBase=mats[0].map?.image;}}
export function appearanceUI(host,state,range,changed){host.replaceChildren();const a=state.appearance;const mode=document.createElement('select');mode.setAttribute('aria-label','Surface mode');for(const [v,t]of [['realistic','Original skin & fabric'],['clay','Clay — inspect shape']]){const o=document.createElement('option');o.value=v;o.textContent=t;mode.append(o);}mode.value=a.mode;mode.onchange=()=>{a.mode=mode.value;changed();};host.append(mode);
const palette=document.createElement('div');palette.setAttribute('aria-label','Skin tone presets');palette.style.cssText='display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:12px 0';
for(const [name,color]of skinPresets){const button=document.createElement('button');button.textContent=name;button.title=name;button.style.cssText='border-left:18px solid '+color+';text-align:left';button.onclick=()=>{a.mode='realistic';a.skin_color=color;a.skin_tint=1;a.skin_lightness=.5;changed();appearanceUI(host,state,range,changed);};palette.append(button);}host.append(palette);
const note=document.createElement('p');note.className='muted';note.textContent='Choose a complexion, then adjust its tint and lightness. Texture detail stays in place; face shape is independent.';host.append(note);
const groups=[['Skin & surface',[['Skin tint strength','skin_tint'],['Skin lightness','skin_lightness'],['Pore and surface detail','skin_detail',2],['Skin roughness','skin_roughness']]],['Pigment & makeup',[['Freckles','freckles'],['Lip color strength','lip_color'],['Eye makeup strength','eye_makeup']]],['Facial lines',[['Forehead lines','forehead'],['Crow’s feet','crow'],['Under-eye lines','under_eye'],['Nose-to-mouth folds','folds'],['Mouth-corner lines','marionette']]],['Hair, brows & outfit',[['Stubble strength','stubble_strength'],['Hair lightness','hair_lightness'],['Brow density','brow_density']]]];
for(const [title,controls]of groups){const details=document.createElement('details');details.open=title==='Skin & surface';const summary=document.createElement('summary');summary.textContent=title;details.append(summary);for(const [label,key,max]of controls)range(details,label,a[key],v=>a[key]=v,max||1);const colors=title==='Skin & surface'?[['Skin tint','skin_color'],['Iris color','iris_color']]:title==='Hair, brows & outfit'?[['Hair tint','hair_color'],['Brow color','brow_color'],['Clothing tint','clothing_color']]:[];for(const [label,key]of colors){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.type='color';input.value=a[key];input.setAttribute('aria-label',label);input.oninput=()=>{a[key]=input.value;changed();};l.append(input);details.append(l);}host.append(details);}}
export function validateAppearance(raw){const a={...appearanceDefaults};if(raw===undefined)return a;for(const k in a){if(!(k in raw))continue;const v=raw[k];if(k==='mode'){if(!['realistic','clay'].includes(v))throw Error('Invalid surface mode');}else if(typeof a[k]==='string'){if(typeof v!=='string'||!/^#[0-9a-f]{6}$/i.test(v))throw Error('Invalid appearance color');}else if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>(k==='skin_detail'?2:1))throw Error('Invalid appearance value');a[k]=v;}return a;}
export function updateAppearance(a){const key=JSON.stringify(a);if(key===signature)return;signature=key;const version=++epoch;
for(const mesh of meshes){const cat=mesh.userData.category,mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];mats.forEach((mat,i)=>{const original=mesh.userData.originalMaterials[i];const realistic=a.mode==='realistic';mat.map=realistic?original.map:null;mat.normalMap=realistic?original.normalMap:null;mat.roughnessMap=realistic?original.roughnessMap:null;mat.color.copy(original.color);if(cat==='body'){mat.color.set(realistic?0xffffff:0xa78b75);mat.normalScale.setScalar(a.skin_detail);mat.roughness=a.skin_roughness;}if(cat==='clothes')mat.color.set(realistic?a.clothing_color:0x526e73);if(cat==='hair'||cat==='beard'){mat.color.set(a.hair_color);if(realistic&&original.map){const c=document.createElement('canvas'),im=original.map.image;c.width=im.width;c.height=im.height;const cx=c.getContext('2d');cx.drawImage(im,0,0);const pixels=cx.getImageData(0,0,c.width,c.height),p=pixels.data,exponent=2**((.5-a.hair_lightness)*2);for(let j=0;j<p.length;j+=4)for(let k=0;k<3;k++)p[j+k]=255*Math.pow(p[j+k]/255,exponent);cx.putImageData(pixels,0,0);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;mat.userData.lightenedHair?.dispose();mat.userData.lightenedHair=texture;mat.map=texture;}else if(!original.map)mat.color.copy(original.color).multiply(new THREE.Color(a.hair_color)).multiplyScalar(2**((a.hair_lightness-.5)*2));}if(cat==='eyebrows'){mat.color.set(a.brow_color);mat.transparent=a.brow_density<1;mat.opacity=a.brow_density;mat.depthWrite=a.brow_density===1;}if(cat==='eyes'&&a.iris_strength&&i===0&&original.map){const im=original.map.image,c=document.createElement('canvas');c.width=im.width;c.height=im.height;const cx=c.getContext('2d');cx.drawImage(im,0,0);const pixels=cx.getImageData(0,0,c.width,c.height),p=pixels.data,rgb=[1,3,5].map(k=>parseInt(a.iris_color.slice(k,k+2),16));for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++){const u=x/c.width,v=y/c.height,r=Math.min(Math.hypot(u-.708,v-.300),Math.hypot(u-.292,v-.708));if(r<.036||r>.113)continue;const j=(y*c.width+x)*4,l=(p[j]*.2126+p[j+1]*.7152+p[j+2]*.0722)/65;const w=Math.min(1,(r-.036)/.008,(.113-r)/.008);for(let k=0;k<3;k++)p[j+k]=p[j+k]*(1-w)+Math.min(255,rgb[k]*l)*w;}cx.putImageData(pixels,0,0);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;mat.userData.irisTexture?.dispose();mat.userData.irisTexture=t;mat.map=t;}mat.needsUpdate=true;});}
if(!skinBase||a.mode==='clay')return;
const canvas=document.createElement('canvas');canvas.width=skinBase.width;canvas.height=skinBase.height;const context=canvas.getContext('2d');context.drawImage(skinBase,0,0);const pixels=context.getImageData(0,0,canvas.width,canvas.height),p=pixels.data,rgb=[1,3,5].map(i=>parseInt(a.skin_color.slice(i,i+2),16)),light=2**((a.skin_lightness-.5)*2);
if(a.skin_tint||a.skin_lightness!==.5){for(let i=0;i<p.length;i+=4){const l=(.2126*p[i]+.7152*p[i+1]+.0722*p[i+2])/170;for(let k=0;k<3;k++)p[i+k]=Math.max(0,Math.min(255,(p[i+k]*(1-a.skin_tint)+rgb[k]*l*Math.pow(Math.max(.05,p[i+k]/Math.max(1,l*170)),.35)*a.skin_tint)*light));}context.putImageData(pixels,0,0);}
if(a.stubble&&stubbleImage.complete&&stubbleImage.naturalWidth){const mask=document.createElement('canvas');mask.width=canvas.width;mask.height=canvas.height;const mc=mask.getContext('2d');mc.drawImage(stubbleImage,0,0,mask.width,mask.height);const alpha=mc.getImageData(0,0,mask.width,mask.height).data,pixels=context.getImageData(0,0,canvas.width,canvas.height);for(let j=0;j<pixels.data.length;j+=4){const strength=alpha[j]/255*.75*a.stubble;for(let k=0;k<3;k++)pixels.data[j+k]*=1-strength;}context.putImageData(pixels,0,0);}
const layers=[['freckles','Freckles','fitted-v1','#704838'],['forehead','Forehead creases','surface-v2','#654b43'],['crow','Crow’s feet / laugh lines','surface-v2','#654b43'],['under_eye','Under-eye fine lines','surface-v2','#654b43'],['folds','Nasolabial folds','surface-v2','#654b43'],['marionette','Marionette lines','surface-v2','#654b43'],['lip_color','Lip color','fitted-v1','#b25b6c'],['eye_makeup','Eye makeup','fitted-v1','#654b43']];
(async()=>{for(const [key,kind,art,color]of layers){if(a[key])await window.avatarGeneratedSkin.apply(context,{kind,art,color,alpha:a[key]},canvas.width,canvas.height);if(version!==epoch)return;}const next=new THREE.CanvasTexture(canvas);next.colorSpace=THREE.SRGBColorSpace;if(skinTexture)skinTexture.dispose();skinTexture=next;for(const m of meshes)if(m.userData.category==='body')m.material.map=next;window.dispatchEvent(new Event('appearance-ready'));})().catch(e=>{if(version===epoch){signature='';document.getElementById('recipeStatus').textContent='Skin detail could not be applied: '+e.message;}});
}
