import {characterCards} from './character-controls.mjs';
const characters=await(await fetch('./characters.json')).json();
import {startingPresets,applyStartingPreset} from './starting-presets.mjs?v=8b';
import {faceStarters,featureStarters,applyFaceStarter,applyFeatureStarter} from './starters.mjs?v=8b';
import * as THREE from 'three';
import {appearanceDefaults,appearanceUI,setupAppearance,updateAppearance,validateAppearance} from './appearance.mjs?v=8b';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),stage=$('stage');
const renderer=makeRenderer();renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0x191e22);renderer.toneMapping=THREE.ACESFilmicToneMapping;stage.prepend(renderer.domElement);
function makeRenderer(){try{return new THREE.WebGLRenderer({antialias:true});}catch(error){
const status=$('status');status.replaceChildren('3D is unavailable in this browser. ');
const a=document.createElement('a');a.href='review.html';a.textContent='View the rendered character comparison';status.append(a);throw error;}}
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(30,1,.01,20),orbit=new OrbitControls(camera,renderer.domElement);
orbit.minDistance=.23;orbit.maxDistance=6;orbit.enablePan=true;
scene.add(new THREE.HemisphereLight(0xe0e9ef,0x827468,2.2));
for(const [p,power] of [[[-2,3,3],1.8],[[2,2,2],.8],[[1,3,-2],1.5]]){const l=new THREE.DirectionalLight(0xffffff,power);l.position.set(...p);scene.add(l);}
function paint(){renderer.render(scene,camera)}window.addEventListener('appearance-ready',paint);orbit.addEventListener('change',paint);
new ResizeObserver(()=>{renderer.setSize(stage.clientWidth,stage.clientHeight);camera.aspect=stage.clientWidth/stage.clientHeight;camera.updateProjectionMatrix();paint()}).observe(stage);
let manifest,state,meshes=[],view='body',pending=false,past=[],future=[],committed;
const bodyFine=new Set(['body_frame','stature','body_mass','muscularity','proportions','shoulder_width','hip_width','torso_length','arm_length','leg_length','head_scale','breast_size','hip_depth','body_softness','body_power']);
const clone=x=>JSON.parse(JSON.stringify(x));
function defaultState(){return {schema:'jnsq-avatar-shape-recipe/9',source_sha256:manifest.source_sha256,head:Object.fromEntries(Object.keys(manifest.heads).map(k=>[k,0])),body:Object.fromEntries(Object.keys(manifest.bodies).map(k=>[k,0])),headRegions:{},bodyRegions:{},fine:Object.fromEntries(manifest.controls.map(([k])=>[k,.5])),expression:Object.fromEntries(manifest.expressions.map(([k])=>[k,0])),hair:true,hairStyle:'ponytail01',beardStyle:'none',browStyle:'eyebrow009',appearance:{...appearanceDefaults}};}
function normalized(values){const total=Math.max(1,Object.values(values).reduce((a,b)=>a+b,0));return Object.fromEntries(Object.entries(values).map(([k,v])=>[k,v/total]));}
function weights(){const result={};for(const kind of ['head','body']){const ids=Object.keys(kind==='head'?manifest.heads:manifest.bodies),regions=manifest[kind+'_regions'],whole=normalized(state[kind]);for(const r of regions){const regional=state[kind+'Regions'][r]||{amount:0,weights:{}};const rw=normalized(regional.weights);for(const id of ids)result[`LIB2_${kind}_${id}_${r}`]=(1-regional.amount)*whole[id]+regional.amount*(rw[id]||0);}}
for(const [id,,low,high]of manifest.controls){result[low]=Math.max(0,(.5-state.fine[id])*2);result[high]=Math.max(0,(state.fine[id]-.5)*2);}for(const [id,,key]of manifest.expressions)result[key]=state.expression[id];const anchors=Object.keys(result).filter(k=>k.startsWith("RANGE9_character_")&&!k.includes("character_age")&&k.endsWith("_Full"));const total=Math.max(1,anchors.reduce((sum,k)=>sum+result[k],0));for(const k of anchors)result[k]/=total;return result;}
function apply(){pending=false;updateAppearance({...state.appearance,stubble:state.beardStyle==='stubble'?state.appearance.stubble_strength:0});const w=weights();for(const mesh of meshes){const category=mesh.userData.category;mesh.visible=category==='hair'?state.hair&&(mesh.userData.style||'classic')===state.hairStyle:category==='beard'?mesh.userData.style===state.beardStyle:category==='eyebrows'?(mesh.userData.style||'classic')===state.browStyle:true;if(!mesh.visible)continue;const {basis,targets}=mesh.userData,a=mesh.geometry.attributes.position.array;a.set(basis);for(const [name,target]of Object.entries(targets)){const v=w[name]||0;if(!v)continue;for(let i=0;i<a.length;i++)a[i]+=v*target[i];}if(mesh.userData.binding){const donor=meshes.find(m=>m.userData.name===mesh.userData.bindingMesh),current=donor.geometry.attributes.position.array,rest=donor.userData.basis;for(let j=0;j<mesh.userData.binding.length;j++){const k=mesh.userData.binding[j]*3;for(let c=0;c<3;c++)a[j*3+c]+=current[k+c]-rest[k+c];}}mesh.geometry.attributes.position.needsUpdate=true;mesh.geometry.computeVertexNormals();weldNormals(mesh);mesh.geometry.computeBoundingBox();}paint();$('status').textContent=`Ready · 6 character starts · independent face and body · ${manifest.controls.length} adjustments`;}
window.addEventListener('stubble-ready',()=>{if(state)schedule();});
function schedule(){if(!pending){pending=true;requestAnimationFrame(apply);}}
function commit(){const next=JSON.stringify(state);if(next!==committed){past.push(committed);if(past.length>50)past.shift();future=[];committed=next;}historyButtons();}
function historyButtons(){$('undo').disabled=!past.length;$('redo').disabled=!future.length;}
function range(host,label,value,oninput,max=1,ends=null){const l=document.createElement('label'),row=document.createElement('span'),o=document.createElement('output'),input=document.createElement('input');row.append(label,o);input.type='range';input.min=0;input.max=max;input.step=.01;input.value=value;input.setAttribute('aria-label',label);o.textContent=Math.round(value*100)+'%';input.oninput=()=>{const v=Number(input.value);o.textContent=Math.round(v*100)+'%';oninput(v);schedule();};input.onchange=commit;l.append(row,input);if(ends){const s=document.createElement('small');s.textContent=ends;l.append(s);}host.append(l);}
function makeMix(kind){const ids=kind==='head'?manifest.heads:manifest.bodies,host=$(kind+'Mix'),presets=$(kind+'Presets');host.replaceChildren();presets.replaceChildren();for(const [id,q]of Object.entries(ids)){const b=document.createElement('button');b.textContent=q.label;b.onclick=()=>{for(const k in state[kind])state[kind][k]=k===id?1:0;state[kind+'Regions']={};refresh();commit();};presets.append(b);range(host,(kind==='head'?'Head: ':'Body: ')+q.label,state[kind][id],v=>state[kind][id]=v);}
const regionHost=$(kind+'Regional');regionHost.replaceChildren();const select=document.createElement('select');select.setAttribute('aria-label',kind+' region');for(const r of manifest[kind+'_regions']){const option=document.createElement('option');option.value=r;option.textContent=r.replaceAll('_',' ');select.append(option);}const sliders=document.createElement('div');regionHost.append(select,sliders);function update(){sliders.replaceChildren();const r=select.value;if(!state[kind+'Regions'][r])state[kind+'Regions'][r]={amount:0,weights:Object.fromEntries(Object.keys(ids).map(k=>[k,0]))};const values=state[kind+'Regions'][r];range(sliders,kind+' regional override',values.amount,v=>values.amount=v);for(const [id,q]of Object.entries(ids))range(sliders,kind+' region: '+q.label,values.weights[id]||0,v=>values.weights[id]=v);}select.onchange=update;update();}
function weldNormals(mesh){const geometry=mesh.geometry,n=geometry.attributes.normal.array;let weld=mesh.userData.weld;if(!weld){const map=new Map(),p=mesh.userData.basis;weld=new Uint32Array(p.length/3);for(let i=0;i<weld.length;i++){const key=[p[i*3],p[i*3+1],p[i*3+2]].map(v=>Math.round(v*1e6)).join(',');if(!map.has(key))map.set(key,map.size);weld[i]=map.get(key);}mesh.userData.weld=weld;mesh.userData.normalSums=new Float32Array(map.size*3);}const sums=mesh.userData.normalSums;sums.fill(0);for(let i=0;i<weld.length;i++)for(let k=0;k<3;k++)sums[weld[i]*3+k]+=n[i*3+k];for(let i=0;i<weld.length;i++){const j=weld[i]*3,l=Math.hypot(sums[j],sums[j+1],sums[j+2])||1;for(let k=0;k<3;k++)n[i*3+k]=sums[j+k]/l;}geometry.attributes.normal.needsUpdate=true;}
function controlMax(id){return id==='brow_height'?1.5:id==='lower_nose_projection'?1.25:1;}
const featureOpen=new Map();
function featureOf(id){if(id.startsWith('head_')&&!bodyFine.has(id))return 'Forehead & face contour';if(id==='anatomy_candidate')return 'Forehead & face contour';if(bodyFine.has(id))return 'Body proportions';if(/nose|nostril|septum/.test(id))return 'Nose';if(/brow/.test(id))return 'Brows';if(/eye|lid/.test(id))return 'Eyes & eyelids';if(/mouth|lip|philtrum|cupids/.test(id))return 'Lips & mouth';if(/jaw|chin/.test(id))return 'Jaw & chin';if(/cheek|temple|nasolabial|midface/.test(id))return 'Cheeks & temples';return 'Forehead & face contour';}
const bodyGroups={'Overall build':['body_softness','body_power','body_frame','stature','body_mass','muscularity','proportions'],'Shoulders & torso':['shoulder_width','torso_length','breast_size'],'Hips & pelvis':['hip_width','hip_depth'],'Arms & legs':['arm_length','leg_length'],'Head size':['head_scale']};
const faceGroups=['Forehead & face contour','Brows','Eyes & eyelids','Nose','Cheeks & temples','Lips & mouth','Jaw & chin'];
function fine(){for(const kind of ['body','face']){const host=$(kind+'Fields');host.replaceChildren();const q=$(kind+'Search').value.toLowerCase();for(const title of kind==='body'?Object.keys(bodyGroups):faceGroups){const belongs=id=>kind==='body'?bodyGroups[title].includes(id):!bodyFine.has(id)&&featureOf(id)===title;const controls=manifest.controls.filter(([id,label])=>belongs(id)&&(!q||label.toLowerCase().includes(q)||title.toLowerCase().includes(q)));if(!controls.length)continue;const details=document.createElement('details');details.className='feature-section';details.open=!!q||(featureOpen.get(title)??false);const summary=document.createElement('summary');summary.textContent=title;details.append(summary);details.ontoggle=()=>{if(details.isConnected&&!q)featureOpen.set(title,details.open);};
if(featureStarters[title]){const row=document.createElement('div');row.className='row';for(const preset of featureStarters[title]){const button=document.createElement('button');button.textContent=preset.name;button.onclick=()=>{applyFeatureStarter(state,preset,title,manifest.controls,featureOf);fine();schedule();commit();};row.append(button);}details.append(row);}
for(const [id,label,low,high]of controls)range(details,label,state.fine[id],v=>state.fine[id]=v,controlMax(id),low.split('_').at(-1)+' → '+high.split('_').at(-1));
const row=document.createElement('div');row.className='row';const reset=document.createElement('button');reset.textContent='Reset '+title.toLowerCase();reset.onclick=()=>{for(const [id]of manifest.controls)if(belongs(id))state.fine[id]=.5;fine();schedule();commit();};row.append(reset);
const vary=document.createElement('button');vary.textContent='Try a variation';vary.onclick=()=>{for(const [id]of manifest.controls)if(belongs(id))state.fine[id]=Math.min(controlMax(id),Math.max(0,state.fine[id]+(Math.random()+Math.random()-1)*.18));fine();schedule();commit();};row.append(vary);details.append(row);host.append(details);}}}
function starterCards(){const host=$('faceStarters');host.replaceChildren();faceStarters.forEach((preset,i)=>{const b=document.createElement('button');const image=document.createElement('img');image.src='asset-face-'+i+'.png';image.alt='';image.style.cssText='width:100%;display:block;border-radius:4px;margin-bottom:5px';b.append(image,preset.name);b.onclick=()=>{applyFaceStarter(state,preset,manifest.controls,bodyFine);refresh();commit();};host.append(b);});}
function refresh(){characterCards($('characterCards'),characters,state,manifest.controls,bodyFine,()=>$('presetScope').value,()=>{refresh();commit();$('recipeStatus').textContent='Character structure applied. Skin, hair and expression are preserved.';});const starters=$('startingPresets');starters.replaceChildren();for(const preset of startingPresets){const button=document.createElement('button');button.textContent=preset.name;button.onclick=()=>{applyStartingPreset(state,preset,manifest.controls,bodyFine,$('presetScope').value);refresh();commit();$('recipeStatus').textContent=preset.name+' starting proportions applied. Every feature remains editable.';};starters.append(button);}starterCards();appearanceUI($('appearanceFields'),state,range,()=>{schedule();commit();});makeMix('body');makeMix('head');fine();$('expressions').replaceChildren();for(const [id,label]of manifest.expressions)range($('expressions'),label,state.expression[id],v=>state.expression[id]=v);for(const [field,list]of [['hairStyle',manifest.hair_styles],['beardStyle',manifest.beard_styles],['browStyle',manifest.brow_styles]]){const select=$(field);select.replaceChildren();for(const item of list){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;select.append(o);}select.value=state[field];}$('hair').checked=state.hair;schedule();historyButtons();}
function frame(which){if(which==='body'||which==='face')view=which;const body=view==='body';let height=.85,depth=.035,width=1.25,tall=1.85;if(meshes.length){if(body){const box=new THREE.Box3();for(const m of meshes)if(m.visible){m.geometry.computeBoundingBox();box.union(m.geometry.boundingBox);}const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());height=center.y;depth=center.z;width=size.x;tall=size.y;}else{const eye=meshes.find(m=>m.userData.category==='eyes');const center=eye.geometry.boundingBox.getCenter(new THREE.Vector3());height=center.y-.025;depth=.035;width=.25;tall=.32;}}else if(!body){height=1.535;width=.22;tall=.32;}
const distance=Math.max(tall,width/Math.max(camera.aspect,.25))/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov/2)))*1.16;const direction=which==='profile'?new THREE.Vector3(1,0,0):which==='quarter'?new THREE.Vector3(.55,.02,.84):new THREE.Vector3(0,0,1);orbit.target.set(0,height,depth);camera.position.copy(orbit.target).addScaledVector(direction.normalize(),distance);orbit.update();paint();}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>frame(b.dataset.view));frame('body');
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);if(b.dataset.tab==='body')frame('body');if(b.dataset.tab==='head'||b.dataset.tab==='expression')frame('face');});
$('bodySearch').oninput=fine;$('faceSearch').oninput=fine;
for(const field of ['beardStyle','browStyle'])$(field).onchange=()=>{state[field]=$(field).value;schedule();commit();};
$('hairStyle').onchange=()=>{state.hairStyle=$('hairStyle').value;state.hair=true;refresh();commit();};
$('studyOn').onclick=()=>{for(const id of ['anatomy_candidate','mouth_candidate','head_atlas','head_rowan','head_ellis','mouth_straight','mouth_full','mouth_bow'])state.fine[id]=.5;state.fine.head_atlas=1;state.fine.mouth_straight=1;refresh();commit();};$('studyOff').onclick=()=>{for(const id of ['anatomy_candidate','mouth_candidate','head_atlas','head_rowan','head_ellis','mouth_straight','mouth_full','mouth_bow'])state.fine[id]=.5;refresh();commit();};
$('hair').onchange=()=>{state.hair=$('hair').checked;schedule();commit();};
$('resetAll').onclick=()=>{state=defaultState();refresh();commit();};$('resetExpression').onclick=()=>{for(const k in state.expression)state.expression[k]=0;refresh();commit();};
$('undo').onclick=()=>{if(!past.length)return;future.push(committed);committed=past.pop();state=JSON.parse(committed);refresh();};$('redo').onclick=()=>{if(!future.length)return;past.push(committed);committed=future.pop();state=JSON.parse(committed);refresh();};
function validateRecipe(raw){if(!raw||!['jnsq-avatar-shape-recipe/2','jnsq-avatar-shape-recipe/3','jnsq-avatar-shape-recipe/4','jnsq-avatar-shape-recipe/5','jnsq-avatar-shape-recipe/6','jnsq-avatar-shape-recipe/7','jnsq-avatar-shape-recipe/8','jnsq-avatar-shape-recipe/9'].includes(raw.schema)||raw.source_sha256!==manifest.source_sha256)throw Error('This recipe belongs to a different library version.');const next=defaultState();function number(v,max=1){if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)throw Error('Recipe contains an invalid weight.');return v;}for(const kind of ['head','body']){for(const id in next[kind])next[kind][id]=number(raw[kind]?.[id]);for(const r of manifest[kind+'_regions']){const src=raw[kind+'Regions']?.[r];if(src){const rw={amount:number(src.amount),weights:{}};for(const id in next[kind])rw.weights[id]=number(src.weights?.[id]??0);next[kind+'Regions'][r]=rw;}}}for(const id in next.fine)next.fine[id]=number(raw.fine?.[id]??(manifest.new_controls.includes(id)?.5:undefined),controlMax(id));if(typeof raw.hair!=='boolean')throw Error('Invalid hair option.');next.hair=raw.hair;next.hairStyle=raw.hairStyle??'classic';if(!manifest.hair_styles.some(x=>x.id===next.hairStyle))throw Error('Invalid hairstyle');next.beardStyle=raw.beardStyle??'none';next.browStyle=raw.browStyle??'classic';if(!manifest.beard_styles.some(x=>x.id===next.beardStyle)||!manifest.brow_styles.some(x=>x.id===next.browStyle))throw Error('Unknown facial hair or brows');next.appearance=validateAppearance(raw.appearance);if(!['jnsq-avatar-shape-recipe/7','jnsq-avatar-shape-recipe/8','jnsq-avatar-shape-recipe/9'].includes(raw.schema))next.appearance.iris_strength=0;return next;}
$('download').onclick=()=>{const recipe=clone(state);delete recipe.expression;const url=URL.createObjectURL(new Blob([JSON.stringify(recipe,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='jnsq-body-face-recipe.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('recipeStatus').textContent='Recipe downloaded. Expression preview excluded.';};
$('import').onclick=()=>$('recipeFile').click();$('recipeFile').onchange=async()=>{try{const f=$('recipeFile').files[0];if(!f)return;if(f.size>1000000)throw Error('Recipe is too large.');const next=validateRecipe(JSON.parse(await f.text()));state=next;refresh();commit();$('recipeStatus').textContent='Recipe loaded.';}catch(e){$('recipeStatus').textContent=e.message;}finally{$('recipeFile').value='';}};
async function load(){manifest=await(await fetch('manifest.json')).json();const [rows,buffer]=await Promise.all([fetch('geometry.json').then(r=>r.json()),fetch('geometry.bin').then(r=>r.arrayBuffer())]);const slice=r=>new Float32Array(buffer,r.offset,r.count);for(const row of rows){const geometry=new THREE.BufferGeometry(),basis=slice(row.position);geometry.setAttribute('position',new THREE.BufferAttribute(new Float32Array(basis),3));geometry.setIndex(row.triangles);if(row.colors)geometry.setAttribute('color',new THREE.BufferAttribute(slice(row.colors),3));geometry.computeVertexNormals();if(row.uv)geometry.setAttribute('uv',new THREE.BufferAttribute(slice(row.uv),2));let map=null;if(row.texture){map=await new THREE.TextureLoader().loadAsync(row.texture);map.colorSpace=THREE.SRGBColorSpace;}const color=row.color??(row.category==='eyebrows'?0x463023:map?0xffffff:row.category==='clothes'?0x526e73:row.category==='eyes'?0x68675f:row.category==='hair'||row.category==='eyebrows'||row.category==='eyelashes'?0x463b33:0xa78b75);const cutout=['hair','beard','eyebrows','eyelashes'].includes(row.category);const mesh=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({color,map,vertexColors:!!row.colors,alphaTest:cutout?.12:0,alphaToCoverage:cutout,roughness:.78,side:THREE.DoubleSide}));if(row.groups){const opaque=mesh.material;mesh.material=row.groups.map((g,i)=>{geometry.addGroup(g.start,g.count,i);return g.cornea?new THREE.MeshStandardMaterial({color:0xffffff,transparent:true,opacity:.08,depthWrite:false,roughness:.12}):opaque;});}if(row.maps){const material=Array.isArray(mesh.material)?mesh.material[0]:mesh.material;for(const [key,slot] of [['normal','normalMap'],['roughness','roughnessMap']])if(row.maps[key]){material[slot]=await new THREE.TextureLoader().loadAsync(row.maps[key]);}material.roughness=row.roughness;material.metalness=row.metalness;}mesh.userData={name:row.name,binding:row.binding?slice(row.binding):null,bindingMesh:row.binding_mesh,style:row.style,category:row.category,basis,targets:Object.fromEntries(Object.entries(row.targets).map(([k,v])=>[k,slice(v)]))};mesh.frustumCulled=false;scene.add(mesh);meshes.push(mesh);}setupAppearance(meshes);state=defaultState();for(const id of ['anatomy_candidate','mouth_candidate','head_atlas','head_rowan','head_ellis','mouth_straight','mouth_full','mouth_bow'])state.fine[id]=.5;refresh();committed=JSON.stringify(state);$('controls').disabled=false;historyButtons();}
load().then(()=>{apply();frame('body');}).catch(e=>{$('status').textContent='Could not load the library: '+e.message;console.error(e);});
